In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from io import StringIO
from urllib import request

from sklearn import cluster, datasets, mixture
from sklearn.neighbors import kneighbors_graph
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing

In [27]:
Geardata = pd.read_csv('/home/claire/IdeaProjects/project_3/gearbox_readings/archive/Run_1.csv',header=None, names=['Input Side Accelerometer','Output Side Accelerometer','Tachometer Reading']) 
Geardata.head(n=5)

Input Side Accelerometer  Output Side Accelerometer  Tachometer Reading
0                  0.012054                   0.003204              4.9133
1                  0.010071                   0.005188              4.9097
2                  0.014954                   0.004883              4.9158
3                  0.014496                   0.005798              4.9158
4                  0.018005                   0.003815              4.9243

In [12]:
min_max_scaler = preprocessing.MinMaxScaler()
Geardata_norm = min_max_scaler.fit_transform(Gear_data)
print(Geardata_norm)

[[0.55437679 0.49717307 0.99233963]
 [0.5406537  0.50384344 0.9916953 ]
 [0.57444585 0.50281718 0.99278708]
 ...
 [0.61245943 0.44432563 0.99103308]
 [0.62090228 0.37403073 0.99257231]
 [0.63146276 0.40430411 0.99212486]]


In [13]:
def normalize(X, axis=-1, p=2):
    lp_norm = np.atleast_1d(np.linalg.norm(X, p, axis))
    lp_norm[lp_norm == 0] = 1
    return X / np.expand_dims(lp_norm, axis)
Geardata_normal = normalize(Gear_data)
print(Geardata_normal)

        Input Side Accelerometer  Output Side Accelerometer  \
0                       0.002453                   0.000652   
1                       0.002051                   0.001057   
2                       0.003042                   0.000993   
3                       0.002949                   0.001180   
4                       0.003656                   0.000775   
...                          ...                        ...   
133323                  0.004166                   0.005720   
133324                  0.003728                   0.001429   
133325                  0.004168                  -0.002550   
133326                  0.004409                  -0.006799   
133327                  0.004721                  -0.004970   

        Tachometer Reading  
0                 0.999997  
1                 0.999997  
2                 0.999995  
3                 0.999995  
4                 0.999993  
...                    ...  
133323            0.999975  
133324     

In [ ]:
from sklearn.cluster import KMeans

# choose K
SSE = []
for k in range(1, 20):
    estimator = KMeans(n_clusters=k)
    estimator.fit(np.array(Geardata_norm))
    SSE.append(estimator.inertia_)
X = range(1, 15)
plt.xlabel('k')
plt.ylabel('SSE')
plt.plot(X, SSE, 'o-')
plt.show()

In [ ]:
y_pred = KMeans(n_clusters=4, random_state=9).fit_predict(file_data)
print(y_pred)